spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

---

spring:
  profiles: local

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:

---

spring:
  profiles: cloud

---