spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  expiration: 864_000_00
  prefix: Bearer
  key:

---

spring:
  profiles: test

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test_mem;MODE=MySQL
    username: sa
    password:
    initialize: true

---

spring:
  profiles: local

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:

---

spring:
  profiles: cloud

---