spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

---

spring:
  profiles: local

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:

---

spring:
  profiles: cloud

---