# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Unit test and build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew -i clean build
    - name: Upload artifact
      run: ./gradlew clean build

  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: todobin jar
        path: build/libs/todobin-*.jar
